all:
	wcl386 -bt=dos -l=dos4g lab1.c
	wcl386 -bt=dos -l=dos4g lab2.c
	wcl386 -bt=dos -l=dos4g lab3.c
	sudo cp lab1.exe ../floppy/PROGS	
	sudo cp lab2.exe ../floppy/PROGS	
	sudo cp lab3.exe ../floppy/PROGS
	sync
